---
title: "第7章"
author: "邬书豪 刘健"
output: github_document
---
          

```{r ,warning=FALSE,message=FALSE}
library(data.table) # fread()
library(tidyverse)    # ggplot()
```

```{r}
responses <- fread("./multipleChoiceResponses")
dim(responses)

responses <- responses[,.(Age,Country,CurrentJobTitleSelect,MLToolNextYearSelect,MLMethodNextYearSelect,EmploymentStatus, FormalEducation,CoursePlatformSelect,FirstTrainingSelect,Tenure,JobSatisfaction,LanguageRecommendationSelect,JobSkillImportanceR,JobSkillImportancePython,JobSkillImportanceSQL,JobSkillImportanceBigData)]

dim(responses)
```

```{r}
responses$Age %>% 
  unique()
responses$Age%>% 
  grep("^1$", x = .)

responses[Age!= 1][,1:2]

```



```{r}
responses$Age <- ifelse(responses$Age %in% c(0:3, 100), 7, responses$Age)
responses[!is.na(Age)]$Age%>% 
  unique()
```


```{r }

df_country_age <- responses %>%
  group_by(Country) %>% 
  summarise(AgeMedian = median(Age, na.rm = T)) %>% 
  arrange(desc(AgeMedian)) 
df_country_age[1:10,]
```



```{r}

df_country_age <- responses[,.(AgeMedian  = median(Age, na.rm = TRUE)), by = .(Country)][order(AgeMedian,decreasing = TRUE)]
```


```{r} 
df_country_age <- df_country_age %>% 
  mutate(Country = ifelse(Country == "New Zealand", "新西兰", Country),
         Country = ifelse(Country == "Spain", "西班牙", 
                          ifelse(Country == "Ireland", "爱尔兰", Country))) 
df_country_age %>% 
  head(3) %>%
  ggplot(aes(x = reorder(Country, AgeMedian), y = AgeMedian,fill = Country)) +
  geom_bar(stat = 'identity') +
  labs(x = "", y = '年龄中位数') +
  geom_text(aes(label = AgeMedian), hjust = 1.5, colour = 'white') +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = 'none') # 移除图例
df_country_age %>% 
  tail(3) %>%
  mutate(Country = case_when(Country == "Pakistan" ~ "巴基斯坦",
                             Country == "Indonesia" ~ "印度尼西亚",
                             Country == "Vietnam" ~ "越南")) %>% 
  ggplot(aes(x = reorder(Country, AgeMedian), y = AgeMedian,fill = Country)) +
  geom_bar(stat = 'identity') +
  labs(x = "", y = '年龄中位数') +
  geom_text(aes(label = AgeMedian), hjust = 1.5, colour = 'white') +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = 'none') 

```


```{r }
# 封装绘图函数
fun1 <- function(data, xlab, ylab, xname, yname) {
  ggplot(data, aes(xlab, ylab)) +
    geom_bar(aes(fill = xlab), stat = 'identity') +
    labs(x = "", y = yname) +
    geom_text(aes(label = ylab), hjust = 1, colour = 'white') +
    coord_flip() +
    theme_minimal() +
    theme(legend.position = 'none')
}

```


```{r }
data <- head(df_country_age, 3)
xname <- ""
yname <- "年龄中位数"
fun1(data, reorder(data$Country, data$AgeMedian), data$AgeMedian, xname, yname)

```



```{r}
df_CJT_USA <- responses %>% # 筛选CurrentJobTitleSelect不为空且美国kaggler的观测
  filter(CurrentJobTitleSelect != '' & Country == 'United States') %>% 
  group_by(CurrentJobTitleSelect) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>% 
  mutate(CurrentJobTitleSelect = case_when(CurrentJobTitleSelect == "Data Scientist" ~ "数据科学家",
                                           CurrentJobTitleSelect == "Software Developer/Software Engineer" ~ "软件开发/工程师",
                                           CurrentJobTitleSelect == "Other" ~ "其他"))
df_CJT_USA$CurrentJobTitleSelect
data <- head(df_CJT_USA, 3)
xname <- ''
yname <- '受访者数量'
fun1(data, reorder(data$CurrentJobTitleSelect, data$Count), data$Count, xname, yname)
```


```{r}
df_CJT_NZ <- responses %>%
  filter(CurrentJobTitleSelect != '' & Country == 'New Zealand') %>%
  group_by(CurrentJobTitleSelect) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>% 
  mutate(CurrentJobTitleSelect = case_when(CurrentJobTitleSelect == "Data Scientist" ~ "数据科学家",
                                           CurrentJobTitleSelect == "Software Developer/Software Engineer" ~ "软件开发/工程师",
                                           CurrentJobTitleSelect == "Other" ~ "其他"))

data <- head(df_CJT_NZ, 3)
xname <- ''
yname <- '受访者数量'
fun1(data, reorder(data$CurrentJobTitleSelect, data$Count), data$Count, xname, yname)

```



```{r }
df_MLT_USA <- responses %>% 
  filter(MLToolNextYearSelect != '' & Country == 'United States') %>%
  group_by(MLToolNextYearSelect) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) 

data <- head(df_MLT_USA, 3)
xname <- '机器学习语言'
yname <- '人数'
fun1(data, reorder(data$MLToolNextYearSelect, data$Count), data$Count, xname, yname)
```


```{r}
df_MLT_NZ <- responses %>% 
  filter(MLToolNextYearSelect != '' & Country == 'New Zealand') %>%
  group_by(MLToolNextYearSelect) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) 

data <- head(df_MLT_NZ, 3)
xname <- '机器学习语言'
yname <- '人数'
fun1(data, reorder(data$MLToolNextYearSelect, data$Count), data$Count, xname, yname)
```




```{r}
df_MLM_USA <- responses %>% 
  filter(MLMethodNextYearSelect != '' & Country == 'United States') %>% 
  group_by(MLMethodNextYearSelect) %>%
  summarise(Count = n()) %>% 
  arrange(desc(Count)) %>% 
  mutate(MLMethodNextYearSelect = case_when(MLMethodNextYearSelect == "Deep learning" ~ "深度学习",
                                           MLMethodNextYearSelect == "Neural Nets" ~ "神经网络",
                                           MLMethodNextYearSelect == "Time Series Analysis" ~ "时间序列分析",
                                           MLMethodNextYearSelect == "Bayesian Methods" ~ "贝叶斯方法",
                                           MLMethodNextYearSelect == "Text Mining" ~ "文本挖掘"))


data <- head(df_MLM_USA, 5)
xname <- '机器学习方法'
yname <- '人数'
fun1(data, reorder(data$MLMethodNextYearSelect, data$Count), data$Count, xname, yname)
```


```{r}
df_MLM_NZ <- responses %>% 
  filter(MLMethodNextYearSelect != '' & Country == 'New Zealand') %>%
  group_by(MLMethodNextYearSelect) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>% 
  mutate(MLMethodNextYearSelect = case_when(MLMethodNextYearSelect == "Deep learning" ~ "深度学习",
                                           MLMethodNextYearSelect == "Neural Nets" ~ "神经网络",
                                           MLMethodNextYearSelect == "Anomaly Detection" ~ "异常检测",
                                           MLMethodNextYearSelect == "Genetic & Evolutionary Algorithms" ~ "遗传进化算法",
                                           MLMethodNextYearSelect == "Time Series Analysis" ~ "时间序列分析"))


data <- head(df_MLM_NZ, 5)
xname <- '机器学习方法'
yname <- '人数'

fun1(data, reorder(data$MLMethodNextYearSelect, data$Count), data$Count, xname, yname)
```

