---
title: "第3章"
author: "刘健"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r cumsum}
x <- c(1:10,NA, 11:20)
cumsum(x)
cumsum(x[-which(is.na(x))])

```

```{r %in%}
df <- tibble(a = 1:6,
             b = letters[1:6])
df %>% 
  filter( a %in% c(1,3,4))
df %>% 
  filter( !a %in% c(1,3,4))
```

```{r diff}
b <- c(1:3,5,7:11,13)
a <- diff(b)
a
diff(b, lag = 2)

length(b)
length(a)

a <- c(NA,diff(b))
a
```
```{r arrange group}
df <- readRDS("RawData/paper_titles.rds")
head(df)


df %>% 
  group_by(year) %>% 
  arrange(titles, .by_group = TRUE) %>% 
  str()
df$year <- as.integer(df$year)
df %>% 
  arrange_if(is.character) %>% 
  head()

```


```{r filter}


df <- readRDS("RawData/paper_titles.rds")
head(df)

df %>% 
  filter(year == 2016 | year == 2017) %>% 
  head()

df %>% 
  filter(year == 2016 & year == 2017) 

df %>% 
  filter(year == 2016 , year == 2017)

df %>% 
  filter(year < 2017 & year > 2015) 



df %>% 
  filter(year != 2017) %>% 
  head()
df %>% 
  filter(!year %in% c(2016,2017)) %>% 
  head()

df %>%
  filter(titles %in% grep("Nitrogen.+", .$titles, value = T))

df %>% 
  filter(is.na(titles)) 


df$year <- as.integer(df$year)
df %>% 
  filter_at(vars(year), any_vars((. %% 4) == 0))

set.seed(42)
df %>% 
  sample_n(size = 5)

df %>% 
  sample_frac(size = 0.3)

df %>% 
  group_by(year) %>% 
  sample_n(size = 2)

df %>% 
  group_by(year) %>% 
  arrange(titles, .by_group = TRUE) %>% 
  filter( titles == first(titles))



```


```{r bind}
df <- readRDS("RawData/paper_titles.rds")
one <- filter(df, year == 2015)
two <- filter(df, year == 2016)
three <- filter(df, year ==2017)
bind_rows(list(a = one, b = two, c = three), .id = "IDs") %>% 
  glimpse()


bind_cols(one[1:3, ], two[1:3, ], three[1:3, ]) %>% 
  glimpse()


```

```{r rename select}
df %>% 
  rename("1" = year) %>% 
  glimpse()
df %>% 
  select("1" = year) %>% 
  glimpse()

df %>% 
  select(starts_with(match = "y"))%>% 
  glimpse()
df %>% 
  select(ends_with(match = "s"))%>% 
  glimpse()

df %>% 
  select(matches(match = ".tle.")) %>% 
  glimpse()

df %>% 
  select(contains(match = "ear")) %>% 
  glimpse()

df %>% 
  select(one_of(... = c("year","titles","day"))) %>% 
  glimpse()


```

$BMI = {WEIGHT}/{HEIGHT^2}$

>30 obese

```{r mutate startwars}
starwars_short <- starwars %>% 
  slice(1:10) %>% 
  select(name, height, mass, species)

starwars_short %>% 
  mutate(height = height/100,
         BMI = mass/(height^2),
         cumprod(mass))

starwars_short %>% 
  mutate(height = height/100,
         BMI = mass/(height^2),
         obese = if_else(BMI > 30, "YES", "NO")) 


starwars_short %>% 
  mutate(height = height/100,
         BMI = mass/(height^2),
         obese = if_else(BMI > 30, "YES", "NO")) %>% 
  filter(species == "Human", obese == "YES")

starwars_short %>% 
  mutate(height = height/100,
         BMI = mass/(height^2),
         obese = case_when(BMI > 30 ~ "YES"))

starwars_short %>% 
  select(-height, -species) %>% 
  mutate(cum_mass = cumsum(mass),
         max_mass = cummax(mass),
         mean_mass = cummean(mass))
starwars_short %>% 
  select(-species) %>% 
  mutate(order = row_number(mass),
         ntile = ntile(height,n = 2),
         diff_heigt = c(NA,diff(height)))

starwars_short %>% 
  mutate_if(.predicate = is.numeric, .funs = as.character) %>% 
  glimpse()
starwars_short %>% 
  mutate_at(.vars = vars(height, mass), .funs = funs(.*10)) %>% 
  glimpse()
starwars_short %>% 
  select(height,mass) %>% 
  mutate_all(.funs = funs(. + 1)) %>% 
  glimpse()

```
```{r mutate text}
df <- readRDS("RawData/paper_titles.rds")
df_cleaned_1 <- df %>% 
  group_by(year) %>% 
  mutate(paperID = 1:n(),
         authors = authors %>% 
           gsub(pattern = "pp\\.\\s\\d.+|\u00A0|\u00F1",replacement = ""),
         titles = titles %>% 
           gsub(pattern = "\u00A0|\u00F1",replacement = ""))
grep("pp\\.\\s\\d.+|\u00A0|\u00F1", x = df_cleaned_1$authors, value = TRUE)
grep("pp\\.\\s\\d.+|\u00A0|\u00F1", x = df_cleaned_1$titles, value = TRUE)
```

```{r summarise}

starwars_short %>% 
  group_by(species) %>% 
  summarise(avg_mass = mean(mass, na.rm = TRUE),
            avg_height = mean(height, na.rm = TRUE),
            n = n(),
            sd_mass = sd(mass, na.rm = TRUE),
            se = sd_mass/sqrt(n))
starwars_short %>% 
  group_by(species) %>% 
  summarise(max_mass = max(mass, na.rm = TRUE),
            min_mass = min(mass, na.rm = TRUE),
            median_mass = median(mass, na.rm = TRUE),
            range_mass = max_mass-min_mass,
            range = diff(range(mass)))

starwars_short %>% 
  group_by(species) %>% 
  summarise(avg_mass = mean(mass, na.rm = TRUE),
            avg_height = mean(height, na.rm = TRUE),
            n = n(),
            sd_mass = sd(mass, na.rm = TRUE),
            se = sd_mass/sqrt(n)) %>% 
  ggplot(aes(species))+
  geom_point(aes(y = avg_mass), shape = 2)+
  geom_point(data = starwars_short, aes(y = mass))+
  geom_errorbar(aes(ymin = avg_mass - se, ymax = avg_mass + se))+
  theme_classic()

starwars_short %>% 
  group_by(species) %>% 
  summarise_all(.funs = funs(mean, sd,.args = list(na.rm = TRUE)))
starwars_short %>% 
  group_by(species) %>% 
  summarise_if(.predicate = is.numeric, .funs = funs(mean, sd, max, min), na.rm = TRUE)
starwars_short %>% 
  group_by(species) %>% 
  summarise_at(.vars = vars(height, mass), .funs = funs(mean, sd, max, min), na.rm = TRUE)

```


```{r text mining}



df_cleaned_1 %>% 
  separate(authors,into = c(paste0("author_", 1:20)), sep = ",|and") %>% 
  gather(key = author_order, value = names, -year, -paperID, -titles) %>% 
  filter(!is.na(names), names!="") %>% 
  group_by(names) %>% 
  count(sort = T) %>% 
  ungroup() %>% 
  top_n(5)%>% 
  mutate(names = fct_reorder(names,n)) %>% 
  ggplot(aes(names,n))+
  geom_point()+
  theme_classic()+
  coord_flip()+
  geom_text(aes(label = n),hjust = -0.3)+
  labs(title = "Top 5 authors")

df_cleaned_1 %>% 
  separate(authors,into = c(paste0("author_", 1:20)), sep = ",|and") %>% 
  gather(key = author_order, value = names, -year, -paperID, -titles) %>% 
  filter(!is.na(names), names!="") %>% 
  mutate(names = gsub("^\\s|\\s$","", names)) %>%
  group_by(names) %>% 
  count(sort = T) %>% 
  ungroup() %>% 
  top_n(5)%>% 
  mutate(names = fct_reorder(names,n)) %>% 
  ggplot(aes(names,n))+
  geom_point()+
  theme_classic()+
  coord_flip()+
  geom_text(aes(label = n),hjust = -0.3)+
  labs(title = "Top 5 authors")


```

