---
title: "第4章"
author: "刘健"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r for}
x <- as.integer(1:5)

cat("1 + 1 =", 1+1, "\n")
cat("1 + 2 =", 1+2, "\n")
cat("1 + 3 =", 1+3, "\n")
cat("1 + 4 =", 1+4, "\n")
cat("1 + 5 =", 1+5, "\n")

for(i in 1:5) cat("1 + ",i, " = ", 1 + i,"\n")




a <- "This is my first loop" %>% 
  strsplit(" ") %>% unlist()
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print(a[5])

for(i in 1:length(a)) print(a[i])
for(i in 1:length(a)) {
  cat("单词",i, "是： ", a[i],"\n")
}
```


```{r}

filenames <- list.files("RawData/", pattern = "*.csv",full.names = T)

data <- list()

for(i in seq_along(filenames)){
  data[[i]] <- read.csv(filenames[i],stringsAsFactors = F)
}
df <- do.call(rbind, data)
str(df)
```

```{r lapply}

# x <- 1:10
# y <- 10:20
# z <- 20:30
# 
# lapply(list(x,y,z), mean)
# 
# x <- c(1:10,NA)
# y <- c(10:20,NA)
# z <- c(20:30,NA)
# lapply(list(x,y,z), mean)
# lapply(list(x,y,z), mean, na.rm = TRUE)
# 
# lapply(list(x,y,z), function(x){
#   mean(x,na.rm = T)
# })
# 
# filenames <- list.files("RawData/", pattern = "*.csv",full.names = T)
# datalist <- lapply(filenames, function(x){
#   df <- read.csv(x,stringsAsFactors = F)
#   df <- df %>% 
#     select(1,3,5)
# 
#   })
# names(datalist)
# df <- do.call(rbind, datalist)
# str(df)


```
```{r sapply}

# x <- 1:10
# y <- 10:20
# z <- 20:30
# 
# sapply(list(x,y,z), mean)
# 
# x <- c(1:10,NA)
# y <- c(10:20,NA)
# z <- c(20:30,NA)
# sapply(list(x,y,z), mean)
# sapply(list(x,y,z), mean, na.rm = TRUE)
# 
# sapply(list(x,y,z), function(x){
#   mean(x,na.rm = T)
# })
# 
# filenames <- list.files("RawData/", pattern = "*.csv",full.names = T)
# datalist <- sapply(filenames, function(x){
#   df <- read.csv(x,stringsAsFactors = F)
# },simplify = F,USE.NAMES = T)
# names(datalist)
# 
# df <- do.call(rbind, datalist)


```


```{r apply}

names(df)
apply(df, 1, mean) %>% as.tibble() %>% .[1:10,]
apply(df, 2, mean) %>% as.tibble()

```
```{r vapply, error=TRUE}

# number1 <- list(as.integer(c(1:5)), as.integer(c(5,2,4,7,1)))
# number2 <- list(as.integer(c(1:4)), as.integer(c(5,2,4,7,1)))
# sapply(number1, function(x) x[x==5] )
# sapply(number2, function(x) x[x==5] )
# vapply(number1, function(x) x[x==5], as.integer(0))
# vapply(number2, function(x) x[x==5], as.integer(0) )
# 
#  
# sapply(1:5, identity)
# 
# sapply(integer(), identity)
# vapply(1:5, identity, as.integer(1))
# vapply(integer(), identity，as.integer(5))

```


```{r rapply}
X <- list("1" = list(a = pi, b = list(c = c(1:2,NA))), "2" = "a test")
X
a <- rapply(X, function(x) x + 1,classes = "numeric", how = "unlist")

rapply(X, mean, classes = "integer", how = "replace", na.rm =TRUE)
rapply(X, mean, classes = "integer", how = "unlist", na.rm =TRUE)


rapply(X, gsub, classes = "character",
       deflt = NA, how = "list", pattern = "\\s", replacement = "")
rapply(X, nchar, classes = "character",
       deflt = as.integer(NA), how = "unlist")
rapply(X, nchar, classes = "character", how = "unlist")
rapply(X, log, classes = "numeric", how = "replace", base = 2)
typeof(as.integer(NA))

```


```{r mapply}
mapply(rep, 1:4, 4:1)

mapply(rep, times = 1:4, x = 4:1)

mapply(rep, times = 1:4, MoreArgs = list( 42))

mapply(function( y,x) y + seq_len(x)  ,
       c(a =  1, b = 2, c = 3),  # names from first
       c(A = 10, B = 0, C = 10),SIMPLIFY = T)

word <- function(C, k) paste(rep.int(LETTERS[1:6], 6:1), collapse = "")
utils::str(mapply(word, LETTERS[1:6], 6:1, SIMPLIFY = T))


```

