---
title: "第6章"
author: "刘健"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(data.table)
library(magrittr)

```

```{r fread}

fread("./RawData/mtcars_DT.csv")
fread("./RawData/mtcars_DT.csv", skip = "Mazda")
fread("./RawData/mtcars_DT.csv", skip = "Mazda RX4")
fread("./RawData/mtcars_DT.csv", skip = "Mazda RX4 Wag")
fread("./RawData/mtcars_DT.csv", skip = "710")
fread("./RawData/mtcars_DT.csv", skip = "Drive")
```

```{r fread_select AND drop}
fread("./RawData/mtcars_DT.csv", select = c("V1","cyl"))
fread("./RawData/mtcars_DT.csv", select = c(1,3))
fread("./RawData/mtcars_DT.csv", drop = "cyl")
fread("./RawData/mtcars_DT.csv", drop = 2)
```
```{r fread_check.names}

df <- mtcars[1:5,1:3]
colnames(df) <- c("V1","V2","V2") 
df
fwrite(df,"./RawData/mtcars_wrongnaming.csv",row.names = TRUE)
fread("./RawData/mtcars_wrongnaming.csv", check.names = TRUE)


```


```{r command lines, error=TRUE}
fread("find /input/projects/processedData/ -type f -name *.csv")
```


```{r i j by, error=TRUE}
DT %>% 
  filter(i) %>% 
  select(j) %>% 
  group_by()
```
```{r i}
DT <- data.table(mtcars,keep.rownames = TRUE)
unique(DT$rn)
DT[rn == "Datsun 710"]

DT[mpg < 18 & cyl == 6 ]

DT[gear == 5 | mpg == 21 ]
```

```{r j}

DT[,.(rn,mpg,cyl)] %>% 
  head()

```
```{r i j}
models <- c("Merc 240D","Merc 230","Merc 280")
DT[rn %in% models, .(rn,mpg,cyl,hp,gear)]
```

```{r by}
DT[, .(mpg_mean = mean(mpg)), by = cyl][order(cyl)]
DT[, .(wt_max = max(wt)), by = cyl][order(cyl)]
DT[, .(hp_max = max(hp)), by = cyl][order(cyl)]
DT[vs == 1 , .(hp_max = max(hp)), by = cyl][order(cyl)]
```
```{r, error=TRUE}

DT_small <- DT[1:3,1:5]

DT_small[, new_col:= "value"][]
DT_small[, new_col_2:= 1:nrow(DT_small)][]
DT_small[, new_col:= NULL][]
DT_small[rn == "Datsun 710", cyl := 0][]

DT_small[mpg > 21, calculte := round(mpg,digits = 0)][]
DT_small[mpg > 21, `:=`(calculte = round(mpg,digits = 0),
                        cyl = 4)][]

```

```{r fwrite}

fwrite(DT_small[,list:= list(1:3,LETTERS[1:3],c("a","b","c"))],sep = "/", sep2 = c("{",",","}"))

```

```{r select}
DT <- data.table(mtcars,keep.rownames = TRUE)

names(DT)
theCols <- names(DT)[c(2:5,7,10)]
one <- DT[,.(mpg,cyl,disp,hp,wt,am)]
two <- DT[, c(2:5,7,10)]

three <- DT[,.SD, .SDcols = theCols]
four <- DT[,..theCols]

identical(one, two)
identical(three, four)
identical(one, four)

names(DT)

setcolorder(DT, order(names(DT)))

head(DT)

setcolorder(DT, c(names(DT)[ncol(DT)],names(DT)[-ncol(DT)]))

head(DT)
```

```{r i based filter}
DT <- data.table(mtcars,keep.rownames = TRUE)


setkey(DT, cyl)
DT[.(6)]
setkey(DT, cyl, carb)
DT[.(4,2)]

Toyota <- grep("Toyota.+", x = DT$rn, value = T)

setkey(DT,rn)

DT[Toyota]
DT[.N]
DT[, .SD[1] , by =.(cyl)]
DT[, .SD[.N] , by =.(cyl)]

DT[, .I[1], by=.(cyl)] 
DT[, .I[.N], by=.(cyl)] 
DT[sample(nrow(DT), 3)]
DT[sample(.N, 3)]
```
j based mutate

```{r j based mutate}
DT <- data.table(mtcars,keep.rownames = TRUE)
str(DT[,1:3])
str(DT[,1:3][, lapply(.SD, as.character)])
str(DT[,1:3][, (2:3) := lapply(.SD, as.factor), .SDcols = 2:3]) #
cols <- colnames(DT)[2:3]
DT[,1:3][, (cols) := lapply(.SD, as.factor), .SDcols = cols]
DT[1:3][, c("Brand","Model") := tstrsplit(rn, split = " ")][]
DT[1:3][, c("Brand","Model") := tstrsplit(rn, split = " ", keep = 1)][]


DT[1:3][, category_1 := ifelse(hp > 240, "A", 
                               ifelse(hp > 150 & hp <= 240, "B", "C"))][]

DT[1:3][, (colnames(DT)):= lapply(.SD, function(x){x = ifelse(x == 0,"--", x)}),.SDcols = colnames(DT)][]


```

```{r JOIN}
set.seed(42)
DT_sampled <- DT[, .SD[sample(.N, 2)], by = cyl][,1:5]
DT_sampled
index_1 <- data.table(value = unique(DT$cyl),
                      index = c(letters[1:3]),
                      comments = c("中等耗油","相对省油","油老虎"))
index_1
DT_sampled[index_1,on = c("cyl"="value")][]
```
```{r long wide trans}

melt(DT_sampled, id.vars = "rn") %>% 
  str()
dcast(melt(DT_sampled, id.vars = "rn"),  rn ~ ...)

```

```{r summarise}





DT[, c(.N, lapply(.SD, mean)), by= .(cyl), .SDcols = 2:5]

DT[, lapply(.SD,mean), by=.(cyl), .SDcols = 2:(ncol(DT)-1)]

DT[, sapply(.SD, function(x) list(mean(x), 
                                  median(x),
                                  max(x))), .SDcols = c("mpg","hp"), by=.(cyl)]


```

